package io.jettra.flux.theme;

/**
 * BitTheme provides factory methods and full CSS/JS design system templates
 * for the Bit theme in JettraFlux.
 */
public class BitTheme {

    public static ThemeData create() {
        return Bit.create();
    }

    public static ThemeData create(ColorMode mode) {
        return Bit.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return Bit.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* BitTheme - Modern Cyan & Dark Navy Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;600;700&family=Fira+Code:wght@400;500&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --primary-color: #00f2fe;\n"
            + "  --secondary-color: #38bdf8;\n"
            + "  --background-color: #080d1a;\n"
            + "  --surface-color: #111827;\n"
            + "  --on-primary-color: #080d1a;\n"
            + "  --on-surface-color: #f3f4f6;\n"
            + "  --text-color: #f3f4f6;\n"
            + "  --text-color-secondary: #9ca3af;\n"
            + "  --border-color: rgba(0, 242, 254, 0.2);\n"
            + "  --border-glow: rgba(0, 242, 254, 0.4);\n"
            + "  --card-bg: rgba(17, 24, 39, 0.85);\n"
            + "  --accent-glow: 0 0 20px rgba(0, 242, 254, 0.25);\n"
            + "  --bs-primary: #00f2fe;\n"
            + "  --bs-secondary: #38bdf8;\n"
            + "  --bs-dark: #080d1a;\n"
            + "  --bs-body-bg: #080d1a;\n"
            + "  --bs-body-color: #f3f4f6;\n"
            + "}\n"
            + "\n"
            + "body {\n"
            + "  background-color: var(--background-color) !important;\n"
            + "  color: var(--on-surface-color) !important;\n"
            + "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "  -webkit-font-smoothing: antialiased;\n"
            + "}\n"
            + "\n"
            + "h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {\n"
            + "  font-family: 'Outfit', sans-serif !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  letter-spacing: -0.02em;\n"
            + "}\n"
            + "\n"
            + "/* JettraFlux Bit Dashboard Layout */\n"
            + ".espresso-dashboard {\n"
            + "  display: grid;\n"
            + "  grid-template-areas: 'top top' 'left center' 'left footer';\n"
            + "  grid-template-columns: 280px 1fr;\n"
            + "  grid-template-rows: 70px minmax(0, 1fr) auto;\n"
            + "  height: 100vh;\n"
            + "  overflow: hidden;\n"
            + "  background-color: var(--background-color);\n"
            + "}\n"
            + "\n"
            + ".espresso-top {\n"
            + "  grid-area: top;\n"
            + "  width: 100%;\n"
            + "  box-sizing: border-box;\n"
            + "  background: rgba(17, 24, 39, 0.95) !important;\n"
            + "  backdrop-filter: blur(16px);\n"
            + "  color: var(--on-surface-color) !important;\n"
            + "  border-bottom: 1px solid var(--border-color);\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.4);\n"
            + "  z-index: 10;\n"
            + "  display: flex;\n"
            + "  align-items: center;\n"
            + "  padding: 0 1.75rem;\n"
            + "}\n"
            + "\n"
            + ".espresso-left {\n"
            + "  grid-area: left;\n"
            + "  height: 100%;\n"
            + "  box-sizing: border-box;\n"
            + "  background: rgba(13, 19, 33, 0.95) !important;\n"
            + "  backdrop-filter: blur(16px);\n"
            + "  color: var(--on-surface-color) !important;\n"
            + "  border-right: 1px solid var(--border-color);\n"
            + "  z-index: 5;\n"
            + "  overflow-y: auto;\n"
            + "  padding: 1.5rem 1rem;\n"
            + "}\n"
            + "\n"
            + ".espresso-center {\n"
            + "  grid-area: center;\n"
            + "  overflow-y: auto;\n"
            + "  width: 100%;\n"
            + "  box-sizing: border-box;\n"
            + "  padding: 2rem;\n"
            + "  background: radial-gradient(circle at 50% 0%, rgba(0, 242, 254, 0.05) 0%, rgba(8, 13, 26, 1) 70%);\n"
            + "  color: var(--on-surface-color);\n"
            + "}\n"
            + "\n"
            + ".espresso-footer {\n"
            + "  grid-area: footer;\n"
            + "  width: 100%;\n"
            + "  box-sizing: border-box;\n"
            + "  padding: 1rem 2rem;\n"
            + "  text-align: center;\n"
            + "  background: rgba(17, 24, 39, 0.9) !important;\n"
            + "  border-top: 1px solid rgba(255, 255, 255, 0.05);\n"
            + "  font-size: 0.875rem;\n"
            + "  color: var(--text-color-secondary);\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Form Controls */\n"
            + ".espresso-textfield, .espresso-textarea, .espresso-select, .espresso-input, .espresso-inputnumber, .form-control, .form-select, input[type=\"text\"], input[type=\"number\"], input[type=\"password\"], input[type=\"email\"], textarea, select {\n"
            + "  background-color: rgba(17, 24, 39, 0.8) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid var(--border-color) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 11px 16px !important;\n"
            + "  font-size: 14px !important;\n"
            + "  width: 100%;\n"
            + "  box-sizing: border-box;\n"
            + "  transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
            + "  backdrop-filter: blur(8px);\n"
            + "}\n"
            + "\n"
            + ".espresso-textfield::placeholder, .espresso-textarea::placeholder, .form-control::placeholder, input::placeholder, textarea::placeholder {\n"
            + "  color: #6b7280 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-textfield:focus, .espresso-textarea:focus, .espresso-select:focus, .espresso-input:focus, .form-control:focus, .form-select:focus, input:focus, textarea:focus, select:focus {\n"
            + "  border-color: #00f2fe !important;\n"
            + "  box-shadow: 0 0 0 3px rgba(0, 242, 254, 0.25), 0 0 15px rgba(0, 242, 254, 0.15) !important;\n"
            + "  outline: none !important;\n"
            + "  background-color: rgba(22, 31, 50, 0.95) !important;\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn-primary, button[type=\"submit\"], button.btn-bit {\n"
            + "  background: linear-gradient(135deg, #00f2fe 0%, #4facfe 100%) !important;\n"
            + "  color: #080d1a !important;\n"
            + "  border: none !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 10px 22px !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  font-size: 14px !important;\n"
            + "  cursor: pointer !important;\n"
            + "  transition: all 0.25s ease !important;\n"
            + "  box-shadow: 0 4px 15px rgba(0, 242, 254, 0.3) !important;\n"
            + "  letter-spacing: 0.01em;\n"
            + "}\n"
            + "\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn-primary:hover, button[type=\"submit\"]:hover {\n"
            + "  transform: translateY(-2px);\n"
            + "  box-shadow: 0 6px 20px rgba(0, 242, 254, 0.45) !important;\n"
            + "  filter: brightness(1.08);\n"
            + "}\n"
            + "\n"
            + ".espresso-button:active, .espresso-btn:active, .btn-primary:active {\n"
            + "  transform: translateY(0);\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Cards & Containers */\n"
            + ".espresso-card, .card, .card-bit {\n"
            + "  background: var(--card-bg) !important;\n"
            + "  backdrop-filter: blur(16px);\n"
            + "  color: #f3f4f6 !important;\n"
            + "  border: 1px solid var(--border-color) !important;\n"
            + "  border-radius: 12px !important;\n"
            + "  padding: 24px !important;\n"
            + "  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4) !important;\n"
            + "  transition: all 0.3s ease;\n"
            + "}\n"
            + "\n"
            + ".espresso-card:hover, .card-bit:hover {\n"
            + "  border-color: var(--border-glow) !important;\n"
            + "  box-shadow: 0 12px 35px rgba(0, 0, 0, 0.5), 0 0 15px rgba(0, 242, 254, 0.1) !important;\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Data Tables */\n"
            + ".espresso-table, .espresso-datatable, .table {\n"
            + "  width: 100%;\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f3f4f6 !important;\n"
            + "  border-collapse: separate !important;\n"
            + "  border-spacing: 0 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-table th, .espresso-datatable th, .table th {\n"
            + "  background-color: rgba(17, 24, 39, 0.95) !important;\n"
            + "  color: #00f2fe !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  font-size: 13px !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  letter-spacing: 0.05em !important;\n"
            + "  padding: 14px 18px !important;\n"
            + "  border-bottom: 2px solid var(--border-color) !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-table td, .espresso-datatable td, .table td {\n"
            + "  padding: 14px 18px !important;\n"
            + "  border-bottom: 1px solid rgba(255, 255, 255, 0.05) !important;\n"
            + "  color: #e5e7eb !important;\n"
            + "  font-size: 14px !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-table tr:hover td, .espresso-datatable tr:hover td, .table tr:hover td {\n"
            + "  background-color: rgba(0, 242, 254, 0.05) !important;\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Alerts */\n"
            + ".espresso-alert, .alert {\n"
            + "  padding: 16px 20px !important;\n"
            + "  border-radius: 10px !important;\n"
            + "  margin-bottom: 20px !important;\n"
            + "  font-weight: 500 !important;\n"
            + "  display: flex !important;\n"
            + "  flex-direction: column !important;\n"
            + "  gap: 6px !important;\n"
            + "  box-sizing: border-box !important;\n"
            + "  backdrop-filter: blur(12px) !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-danger, .alert-danger {\n"
            + "  background-color: rgba(239, 68, 68, 0.15) !important;\n"
            + "  border: 1px solid rgba(239, 68, 68, 0.4) !important;\n"
            + "  color: #fca5a5 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-danger * {\n"
            + "  color: #fca5a5 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-success, .alert-success {\n"
            + "  background-color: rgba(16, 185, 129, 0.15) !important;\n"
            + "  border: 1px solid rgba(16, 185, 129, 0.4) !important;\n"
            + "  color: #6ee7b7 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-success * {\n"
            + "  color: #6ee7b7 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-info, .alert-info {\n"
            + "  background-color: rgba(0, 242, 254, 0.15) !important;\n"
            + "  border: 1px solid rgba(0, 242, 254, 0.4) !important;\n"
            + "  color: #38bdf8 !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-alert-info * {\n"
            + "  color: #38bdf8 !important;\n"
            + "}\n"
            + "\n"
            + "/* Bit Theme Scrollbars */\n"
            + "::-webkit-scrollbar {\n"
            + "  width: 8px;\n"
            + "  height: 8px;\n"
            + "}\n"
            + "::-webkit-scrollbar-track {\n"
            + "  background: #080d1a;\n"
            + "}\n"
            + "::-webkit-scrollbar-thumb {\n"
            + "  background: rgba(0, 242, 254, 0.25);\n"
            + "  border-radius: 4px;\n"
            + "}\n"
            + "::-webkit-scrollbar-thumb:hover {\n"
            + "  background: rgba(0, 242, 254, 0.5);\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "console.log('[BitTheme] Theme initialized successfully.');\n"
            + "</script>";
    }
}
