package io.jettra.flux.theme;

/**
 * GamesTheme provides an authentic 3D arcade / gaming HUD visual theme for JettraFlux,
 * modeled 100% after the screen design and components seen in JettraStore 3D:
 * - Deep space dark canvas (#040610) with 3D perspective cyber grid in luminous cyan
 * - Games Gold (#ffd700) primary actions, JETTRA CORE header, modal frames, and event logs
 * - Cyber Sky Blue (#00d4ff) secondary accents, JAVA 25 EDITION subtitle, entity IDs and telemetry
 * - Neon Tactical Lime (#22c55e) online node badges, SAVE STATE, and action buttons
 * - Neon Alert Red (#ef4444) for RESET JETTRASTORE, offline indicators, and close buttons
 * - Arcade Synth Purple (#a855f7) and Arcade Orange (#f59e0b) for chat, help and versions
 * - Console-style action buttons with bracket labels ([CONN], [USERS], [ENGINES], [RESET], etc.)
 * - Full modal layouts for Database Technical Sheets and Multimodel Object Explorers
 * - Interactive 3D perspective grid canvas background in pure vanilla JavaScript
 * - Pure HTML, CSS, JavaScript (zero external UI dependencies)
 */
public class GamesTheme {

    public static ThemeData create() {
        return Games.create();
    }

    public static ThemeData create(ColorMode mode) {
        return Games.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return Games.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* JettraStore Games 3D Gaming & HUD Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700;800&family=Orbitron:wght@500;700;900&family=Inter:wght@400;500;600;700&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --games-gold: #ffd700;\n"
            + "  --games-gold-glow: rgba(255, 215, 0, 0.45);\n"
            + "  --games-blue: #00d4ff;\n"
            + "  --games-blue-glow: rgba(0, 212, 255, 0.45);\n"
            + "  --games-lime: #22c55e;\n"
            + "  --games-lime-glow: rgba(34, 197, 94, 0.45);\n"
            + "  --games-red: #ef4444;\n"
            + "  --games-red-glow: rgba(239, 68, 68, 0.45);\n"
            + "  --games-purple: #a855f7;\n"
            + "  --games-orange: #f59e0b;\n"
            + "  --games-bg: #040610;\n"
            + "  --games-surface: #0e1220;\n"
            + "  --games-surface-alt: #141a2e;\n"
            + "  --games-border-gold: #ffd700;\n"
            + "  --games-border-blue: rgba(0, 212, 255, 0.35);\n"
            + "  --games-text: #f8fafc;\n"
            + "  --games-text-muted: #94a3b8;\n"
            + "  --games-font: 'JetBrains Mono', 'Orbitron', 'Segoe UI', monospace, sans-serif;\n"
            + "  --background-color: #040610 !important;\n"
            + "  --surface-color: #0e1220 !important;\n"
            + "  --on-surface-color: #f8fafc !important;\n"
            + "  --on-primary-color: #040610 !important;\n"
            + "  --primary-color: #ffd700 !important;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "body, p, h1, h2, h3, h4, h5, h6, input, textarea, select, button, table, a, div {\n"
            + "  font-family: var(--games-font);\n"
            + "  -webkit-font-smoothing: antialiased;\n"
            + "  -moz-osx-font-smoothing: grayscale;\n"
            + "}\n"
            + "\n"
            + "/* Preserve icon font families */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "}\n"
            + "\n"
            + "/* Body Canvas with 3D Cyber Perspective Grid */\n"
            + "body {\n"
            + "  background-color: #040610 !important;\n"
            + "  background-image:\n"
            + "    linear-gradient(rgba(0, 212, 255, 0.08) 1px, transparent 1px),\n"
            + "    linear-gradient(90deg, rgba(0, 212, 255, 0.08) 1px, transparent 1px) !important;\n"
            + "  background-size: 32px 32px !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "  overflow-x: hidden;\n"
            + "  position: relative;\n"
            + "}\n"
            + "\n"
            + "/* Custom Game HUD Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #040610; }\n"
            + "::-webkit-scrollbar-thumb { background: #161e32; border-radius: 4px; border: 1px solid rgba(0, 212, 255, 0.3); }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #00d4ff; box-shadow: 0 0 10px #00d4ff; }\n"
            + "\n"
            + "/* Layout & Viewports */\n"
            + ".espresso-dashboard, .espresso-center, .espresso-main, .jettra-main-viewport, .games-center {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Top Header Bar */\n"
            + ".espresso-top, .games-top, .jettra-header {\n"
            + "  background-color: #080c18 !important;\n"
            + "  border-bottom: 2px solid #ffd700 !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.85), 0 0 15px rgba(255, 215, 0, 0.15) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Right / Left HUD Sidebar */\n"
            + ".espresso-left, .games-sidebar, .jettra-sidebar {\n"
            + "  background-color: rgba(10, 15, 28, 0.95) !important;\n"
            + "  backdrop-filter: blur(12px) !important;\n"
            + "  border-right: 1px solid rgba(0, 212, 255, 0.3) !important;\n"
            + "  box-shadow: 4px 0 24px rgba(0, 0, 0, 0.7) !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-left a, .espresso-left p, .games-sidebar a, .games-sidebar p, .widgetlet-item {\n"
            + "  color: #94a3b8 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 5px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 600;\n"
            + "  border: 1px solid transparent;\n"
            + "}\n"
            + "\n"
            + ".espresso-left a:hover, .espresso-left p:hover, .games-sidebar a:hover, .games-sidebar p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(0, 212, 255, 0.12) !important;\n"
            + "  color: #00d4ff !important;\n"
            + "  border-color: rgba(0, 212, 255, 0.45) !important;\n"
            + "  text-shadow: 0 0 10px rgba(0, 212, 255, 0.6);\n"
            + "  transform: translateX(4px);\n"
            + "}\n"
            + "\n"
            + ".espresso-left a.active, .games-sidebar a.active {\n"
            + "  background-color: rgba(255, 215, 0, 0.14) !important;\n"
            + "  color: #ffd700 !important;\n"
            + "  border-left: 3px solid #ffd700 !important;\n"
            + "  border-color: rgba(255, 215, 0, 0.5) !important;\n"
            + "  box-shadow: 0 0 15px rgba(255, 215, 0, 0.3);\n"
            + "  font-weight: 700;\n"
            + "}\n"
            + "\n"
            + "/* JETTRA CORE Gaming Titles */\n"
            + ".games-title-core {\n"
            + "  color: #ffd700 !important;\n"
            + "  font-weight: 900 !important;\n"
            + "  font-size: 1.35rem !important;\n"
            + "  letter-spacing: 0.12em !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  text-shadow: 0 0 12px rgba(255, 215, 0, 0.6) !important;\n"
            + "  margin: 0;\n"
            + "}\n"
            + "\n"
            + ".games-subtitle-edition {\n"
            + "  color: #00d4ff !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  font-size: 0.75rem !important;\n"
            + "  letter-spacing: 0.15em !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  text-shadow: 0 0 8px rgba(0, 212, 255, 0.5) !important;\n"
            + "  margin-top: 2px;\n"
            + "  margin-bottom: 12px;\n"
            + "}\n"
            + "\n"
            + "/* Console Action Buttons with Bracketed Game Style */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary, .games-btn, .games-btn-gold {\n"
            + "  background: linear-gradient(180deg, #ffd700 0%, #d4af37 100%) !important;\n"
            + "  color: #040610 !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 14px rgba(255, 215, 0, 0.45) !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  letter-spacing: 0.08em !important;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n"
            + "}\n"
            + "\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover, .games-btn-gold:hover {\n"
            + "  background: #ffea00 !important;\n"
            + "  border-color: #ffffff !important;\n"
            + "  box-shadow: 0 0 22px rgba(255, 215, 0, 0.75) !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + "\n"
            + ".espresso-button:active, .games-btn-gold:active {\n"
            + "  transform: translateY(1px);\n"
            + "}\n"
            + "\n"
            + "/* Sky Blue Game Button: [USERS], [EDIT], etc. */\n"
            + ".games-btn-blue, .espresso-btn-info, .btn-info {\n"
            + "  background: linear-gradient(180deg, rgba(0, 212, 255, 0.85) 0%, rgba(2, 132, 199, 0.85) 100%) !important;\n"
            + "  color: #040610 !important;\n"
            + "  border: 1px solid #00d4ff !important;\n"
            + "  box-shadow: 0 0 12px rgba(0, 212, 255, 0.4) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-btn-blue:hover, .espresso-btn-info:hover, .btn-info:hover {\n"
            + "  background: #00d4ff !important;\n"
            + "  border-color: #ffffff !important;\n"
            + "  box-shadow: 0 0 20px rgba(0, 212, 255, 0.75) !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + "\n"
            + "/* Lime Green Game Button: [ENGINES], [GUARDAR], [+] AGREGAR, BUSCAR */\n"
            + ".games-btn-lime, .espresso-btn-success, .btn-success {\n"
            + "  background: linear-gradient(180deg, #22c55e 0%, #16a34a 100%) !important;\n"
            + "  color: #040610 !important;\n"
            + "  border: 1px solid #22c55e !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 12px rgba(34, 197, 94, 0.45) !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-btn-lime:hover, .espresso-btn-success:hover, .btn-success:hover {\n"
            + "  background: #34d399 !important;\n"
            + "  box-shadow: 0 0 20px rgba(34, 197, 94, 0.75) !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + "\n"
            + "/* Alert Red Game Button: [RESET], [ELIM], DESCONECTAR, [X] */\n"
            + ".games-btn-red, .espresso-btn-danger, .btn-danger {\n"
            + "  background: linear-gradient(180deg, #ef4444 0%, #dc2626 100%) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid #ef4444 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 12px rgba(239, 68, 68, 0.45) !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-btn-red:hover, .espresso-btn-danger:hover, .btn-danger:hover {\n"
            + "  background: #f87171 !important;\n"
            + "  box-shadow: 0 0 20px rgba(239, 68, 68, 0.75) !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + "\n"
            + "/* Synth Purple Game Button: ABRIR CHAT, (?) AYUDA */\n"
            + ".games-btn-purple {\n"
            + "  background: linear-gradient(180deg, #a855f7 0%, #7e22ce 100%) !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid #a855f7 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 12px rgba(168, 85, 247, 0.4) !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-btn-purple:hover {\n"
            + "  background: #c084fc !important;\n"
            + "  box-shadow: 0 0 20px rgba(168, 85, 247, 0.7) !important;\n"
            + "  transform: translateY(-2px);\n"
            + "}\n"
            + "\n"
            + "/* Neutral Dark Game Button: CENTER MAP, SALIR, LIMPIAR, ZOOM */\n"
            + ".games-btn-dark {\n"
            + "  background: #1e293b !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  border: 1px solid rgba(255, 255, 255, 0.2) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  padding: 8px 16px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-btn-dark:hover {\n"
            + "  background: #334155 !important;\n"
            + "  border-color: #00d4ff !important;\n"
            + "  color: #00d4ff !important;\n"
            + "}\n"
            + "\n"
            + "/* Tactical HUD Cards & Container Surfaces */\n"
            + ".espresso-card, .games-card, .games-hud-panel, .card {\n"
            + "  background: linear-gradient(180deg, rgba(16, 22, 38, 0.95) 0%, rgba(9, 13, 22, 0.98) 100%) !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 20px !important;\n"
            + "  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.8), inset 0 1px 0 rgba(255, 215, 0, 0.2) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  position: relative;\n"
            + "  transition: border-color 0.25s, box-shadow 0.25s;\n"
            + "}\n"
            + "\n"
            + ".espresso-card:hover, .games-card:hover {\n"
            + "  box-shadow: 0 6px 28px rgba(0, 0, 0, 0.9), 0 0 15px rgba(255, 215, 0, 0.25) !important;\n"
            + "}\n"
            + "\n"
            + "/* Card with Skyblue Border Variant */\n"
            + ".games-card-blue {\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.45) !important;\n"
            + "  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.8), 0 0 15px rgba(0, 212, 255, 0.2) !important;\n"
            + "}\n"
            + "\n"
            + "/* Modal Windows: FICHA TÉCNICA (Fig 3) & EXPLORADOR MULTIMODELO (Fig 4) */\n"
            + ".games-modal {\n"
            + "  background: rgba(14, 18, 32, 0.96) !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  box-shadow: 0 0 40px rgba(0, 0, 0, 0.9), 0 0 20px rgba(255, 215, 0, 0.25) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  overflow: hidden !important;\n"
            + "}\n"
            + "\n"
            + ".games-modal-header {\n"
            + "  background: #181e30 !important;\n"
            + "  border-bottom: 2px solid #ffd700 !important;\n"
            + "  padding: 12px 18px !important;\n"
            + "  display: flex !important;\n"
            + "  align-items: center !important;\n"
            + "  justify-content: space-between !important;\n"
            + "}\n"
            + "\n"
            + ".games-modal-title {\n"
            + "  color: #ffd700 !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 1rem !important;\n"
            + "  letter-spacing: 0.08em !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  margin: 0 !important;\n"
            + "}\n"
            + "\n"
            + ".games-modal-close {\n"
            + "  background: #ef4444 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: none !important;\n"
            + "  border-radius: 4px !important;\n"
            + "  width: 28px !important;\n"
            + "  height: 25px !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  cursor: pointer !important;\n"
            + "  display: flex !important;\n"
            + "  align-items: center !important;\n"
            + "  justify-content: center !important;\n"
            + "  transition: background 0.2s;\n"
            + "}\n"
            + "\n"
            + ".games-modal-close:hover {\n"
            + "  background: #f87171 !important;\n"
            + "  box-shadow: 0 0 10px #ef4444 !important;\n"
            + "}\n"
            + "\n"
            + "/* Console Tabs: [OBJ] REGISTROS Y OBJETOS (CRUD) / [IDX] */\n"
            + ".games-tabs {\n"
            + "  display: flex;\n"
            + "  gap: 4px;\n"
            + "  margin-bottom: 12px;\n"
            + "}\n"
            + "\n"
            + ".games-tab-active {\n"
            + "  background: #ffd700 !important;\n"
            + "  color: #040610 !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 4px 4px 0 0 !important;\n"
            + "  padding: 6px 14px !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 0.8rem !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  cursor: pointer;\n"
            + "}\n"
            + "\n"
            + ".games-tab-inactive {\n"
            + "  background: #181e30 !important;\n"
            + "  color: #94a3b8 !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.2) !important;\n"
            + "  border-radius: 4px 4px 0 0 !important;\n"
            + "  padding: 6px 14px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  font-size: 0.8rem !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  cursor: pointer;\n"
            + "}\n"
            + "\n"
            + ".games-tab-inactive:hover {\n"
            + "  color: #00d4ff !important;\n"
            + "  border-color: #00d4ff !important;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs and Search Bar */\n"
            + ".espresso-textfield, input[type=\"text\"], input[type=\"password\"], input[type=\"search\"], select, textarea {\n"
            + "  background-color: #060914 !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.4) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  font-family: var(--games-font) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 8px 14px !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + "\n"
            + ".espresso-textfield:focus, input:focus, select:focus, textarea:focus {\n"
            + "  border-color: #ffd700 !important;\n"
            + "  box-shadow: 0 0 14px rgba(255, 215, 0, 0.5) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "\n"
            + "/* DataTables & Data Grids */\n"
            + ".espresso-datatable, table {\n"
            + "  border-collapse: separate !important;\n"
            + "  border-spacing: 0 !important;\n"
            + "  width: 100% !important;\n"
            + "  background-color: #0e1220 !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable th, table th {\n"
            + "  background-color: #12182a !important;\n"
            + "  color: #ffd700 !important;\n"
            + "  border-bottom: 2px solid #ffd700 !important;\n"
            + "  padding: 12px 16px !important;\n"
            + "  text-align: left !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  font-size: 0.8rem !important;\n"
            + "  letter-spacing: 0.08em !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable td, table td {\n"
            + "  padding: 10px 16px !important;\n"
            + "  border-bottom: 1px solid rgba(0, 212, 255, 0.18) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable tr:hover td, table tr:hover td {\n"
            + "  background-color: rgba(0, 212, 255, 0.1) !important;\n"
            + "  color: #ffffff !important;\n"
            + "}\n"
            + "\n"
            + "/* Multimodel Record Cards (Fig 4) */\n"
            + ".games-record-card {\n"
            + "  background: #0b0f1e !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.35) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 8px !important;\n"
            + "  display: flex !important;\n"
            + "  justify-content: space-between !important;\n"
            + "  align-items: center !important;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".games-record-card:hover {\n"
            + "  border-color: #ffd700 !important;\n"
            + "  box-shadow: 0 0 12px rgba(255, 215, 0, 0.3) !important;\n"
            + "  transform: translateX(3px);\n"
            + "}\n"
            + "\n"
            + ".games-record-id {\n"
            + "  color: #00d4ff !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "  margin-right: 8px;\n"
            + "}\n"
            + "\n"
            + "/* Buckets List Row (Fig 3) */\n"
            + ".games-bucket-row {\n"
            + "  background: rgba(14, 22, 40, 0.85) !important;\n"
            + "  border: 1px solid #0284c7 !important;\n"
            + "  border-radius: 4px !important;\n"
            + "  padding: 7px 12px !important;\n"
            + "  margin-bottom: 5px !important;\n"
            + "  color: #38bdf8 !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "  font-weight: 600 !important;\n"
            + "  display: flex !important;\n"
            + "  align-items: center !important;\n"
            + "  gap: 8px !important;\n"
            + "  transition: all 0.15s ease;\n"
            + "}\n"
            + "\n"
            + ".games-bucket-row:hover {\n"
            + "  background: rgba(2, 132, 199, 0.25) !important;\n"
            + "  border-color: #00d4ff !important;\n"
            + "  color: #ffffff !important;\n"
            + "  transform: translateX(2px);\n"
            + "}\n"
            + "\n"
            + "/* System Event Log (Fig 1) */\n"
            + ".games-event-log {\n"
            + "  background: rgba(0, 0, 0, 0.88) !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 14px 18px !important;\n"
            + "  font-family: var(--games-font) !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.85) !important;\n"
            + "}\n"
            + "\n"
            + ".games-event-log-title {\n"
            + "  color: #ffd700 !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 0.85rem !important;\n"
            + "  letter-spacing: 0.08em !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  margin-bottom: 8px !important;\n"
            + "}\n"
            + "\n"
            + ".games-log-timestamp {\n"
            + "  color: #ef4444 !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  margin-right: 6px;\n"
            + "}\n"
            + "\n"
            + "/* Live Feed Widget (Fig 1) */\n"
            + ".games-live-feed {\n"
            + "  background: rgba(0, 0, 0, 0.75) !important;\n"
            + "  border-radius: 4px !important;\n"
            + "  padding: 8px 12px !important;\n"
            + "  font-family: var(--games-font) !important;\n"
            + "}\n"
            + "\n"
            + ".games-live-feed-title {\n"
            + "  color: #ffd700 !important;\n"
            + "  font-weight: 800 !important;\n"
            + "  font-size: 0.8rem !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  margin-bottom: 4px !important;\n"
            + "}\n"
            + "\n"
            + "/* Badges & Node Status Bullets */\n"
            + ".games-badge {\n"
            + "  display: inline-flex;\n"
            + "  align-items: center;\n"
            + "  gap: 6px;\n"
            + "  padding: 3px 10px;\n"
            + "  border-radius: 9999px;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-weight: 800;\n"
            + "  letter-spacing: 0.06em;\n"
            + "  text-transform: uppercase;\n"
            + "}\n"
            + "\n"
            + ".games-badge-leader, .games-badge-lime {\n"
            + "  color: #22c55e;\n"
            + "  border: 1px solid #22c55e;\n"
            + "  background-color: rgba(34, 197, 94, 0.12);\n"
            + "  box-shadow: 0 0 10px rgba(34, 197, 94, 0.3);\n"
            + "}\n"
            + "\n"
            + ".games-badge-offline, .games-badge-red {\n"
            + "  color: #ef4444;\n"
            + "  border: 1px solid #ef4444;\n"
            + "  background-color: rgba(239, 68, 68, 0.12);\n"
            + "  box-shadow: 0 0 10px rgba(239, 68, 68, 0.3);\n"
            + "}\n"
            + "\n"
            + ".games-badge-blue {\n"
            + "  color: #00d4ff;\n"
            + "  border: 1px solid #00d4ff;\n"
            + "  background-color: rgba(0, 212, 255, 0.12);\n"
            + "  box-shadow: 0 0 10px rgba(0, 212, 255, 0.3);\n"
            + "}\n"
            + "\n"
            + ".games-badge-gold {\n"
            + "  color: #ffd700;\n"
            + "  border: 1px solid #ffd700;\n"
            + "  background-color: rgba(255, 215, 0, 0.12);\n"
            + "  box-shadow: 0 0 10px rgba(255, 215, 0, 0.3);\n"
            + "}\n"
            + "\n"
            + "/* Pulsing node status indicator */\n"
            + "@keyframes games-pulse {\n"
            + "  0% { transform: scale(0.9); opacity: 0.6; }\n"
            + "  50% { transform: scale(1.25); opacity: 1; }\n"
            + "  100% { transform: scale(0.9); opacity: 0.6; }\n"
            + "}\n"
            + "\n"
            + ".games-dot-active {\n"
            + "  display: inline-block;\n"
            + "  width: 8px;\n"
            + "  height: 8px;\n"
            + "  border-radius: 50%;\n"
            + "  background-color: #22c55e;\n"
            + "  box-shadow: 0 0 10px #22c55e;\n"
            + "  animation: games-pulse 1.8s infinite;\n"
            + "  margin-right: 6px;\n"
            + "}\n"
            + "\n"
            + ".games-dot-alert {\n"
            + "  display: inline-block;\n"
            + "  width: 8px;\n"
            + "  height: 8px;\n"
            + "  border-radius: 50%;\n"
            + "  background-color: #ef4444;\n"
            + "  box-shadow: 0 0 10px #ef4444;\n"
            + "  margin-right: 6px;\n"
            + "}\n"
            + "\n"
            + "/* Bottom Help & Navigation Bar (Fig 2) */\n"
            + ".games-bottom-bar {\n"
            + "  position: fixed;\n"
            + "  bottom: 0;\n"
            + "  left: 0;\n"
            + "  width: 100%;\n"
            + "  height: 38px;\n"
            + "  background: rgba(0, 0, 0, 0.88);\n"
            + "  border-top: 1px solid rgba(255, 255, 255, 0.2);\n"
            + "  display: flex;\n"
            + "  align-items: center;\n"
            + "  padding: 0 24px;\n"
            + "  font-size: 0.8rem;\n"
            + "  color: #f8fafc;\n"
            + "  z-index: 100;\n"
            + "}\n"
            + "\n"
            + "/* 3D Perspective Grid Background Canvas */\n"
            + "#games-perspective-grid-canvas {\n"
            + "  position: fixed;\n"
            + "  top: 0;\n"
            + "  left: 0;\n"
            + "  width: 100vw;\n"
            + "  height: 100vh;\n"
            + "  z-index: -1;\n"
            + "  pointer-events: none;\n"
            + "  opacity: 0.75;\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "(function() {\n"
            + "  function initGamesPerspectiveGrid() {\n"
            + "    if (document.getElementById('games-perspective-grid-canvas')) return;\n"
            + "    var canvas = document.createElement('canvas');\n"
            + "    canvas.id = 'games-perspective-grid-canvas';\n"
            + "    document.body.prepend(canvas);\n"
            + "\n"
            + "    var ctx = canvas.getContext('2d');\n"
            + "    var w, h;\n"
            + "\n"
            + "    function resize() {\n"
            + "      w = canvas.width = window.innerWidth;\n"
            + "      h = canvas.height = window.innerHeight;\n"
            + "    }\n"
            + "    resize();\n"
            + "    window.addEventListener('resize', resize);\n"
            + "\n"
            + "    var offset = 0;\n"
            + "    var lastTime = 0;\n"
            + "    function render(time) {\n"
            + "      requestAnimationFrame(render);\n"
            + "      if (time - lastTime < 33) return; // ~30 fps cap\n"
            + "      lastTime = time;\n"
            + "\n"
            + "      ctx.clearRect(0, 0, w, h);\n"
            + "\n"
            + "      // Perspective Horizon Grid (JettraStore 3D Plane simulation)\n"
            + "      var horizonY = h * 0.38;\n"
            + "      var vanishX = w * 0.5;\n"
            + "\n"
            + "      ctx.save();\n"
            + "      ctx.strokeStyle = 'rgba(0, 212, 255, 0.12)';\n"
            + "      ctx.lineWidth = 1;\n"
            + "\n"
            + "      // Radiating perspective lines\n"
            + "      var numLines = 36;\n"
            + "      for (var i = -numLines; i <= numLines; i++) {\n"
            + "        var bottomX = vanishX + (i * (w / 18));\n"
            + "        ctx.beginPath();\n"
            + "        ctx.moveTo(vanishX, horizonY);\n"
            + "        ctx.lineTo(bottomX, h);\n"
            + "        ctx.stroke();\n"
            + "      }\n"
            + "\n"
            + "      // Transverse receding lines\n"
            + "      var transverseCount = 20;\n"
            + "      for (var j = 1; j <= transverseCount; j++) {\n"
            + "        var t = (j + (offset % 1)) / transverseCount;\n"
            + "        var y = horizonY + Math.pow(t, 2.2) * (h - horizonY);\n"
            + "        var alpha = Math.min(0.25, t * 0.28);\n"
            + "        ctx.strokeStyle = 'rgba(0, 212, 255, ' + alpha + ')';\n"
            + "        ctx.beginPath();\n"
            + "        ctx.moveTo(0, y);\n"
            + "        ctx.lineTo(w, y);\n"
            + "        ctx.stroke();\n"
            + "      }\n"
            + "\n"
            + "      // Subtle glow at horizon center\n"
            + "      var grad = ctx.createRadialGradient(vanishX, horizonY, 0, vanishX, horizonY, w * 0.45);\n"
            + "      grad.addColorStop(0, 'rgba(0, 212, 255, 0.08)');\n"
            + "      grad.addColorStop(0.5, 'rgba(255, 215, 0, 0.03)');\n"
            + "      grad.addColorStop(1, 'transparent');\n"
            + "      ctx.fillStyle = grad;\n"
            + "      ctx.fillRect(0, 0, w, h);\n"
            + "\n"
            + "      ctx.restore();\n"
            + "      offset += 0.005;\n"
            + "    }\n"
            + "    requestAnimationFrame(render);\n"
            + "  }\n"
            + "  if (document.readyState === 'loading') {\n"
            + "    document.addEventListener('DOMContentLoaded', initGamesPerspectiveGrid);\n"
            + "  } else {\n"
            + "    initGamesPerspectiveGrid();\n"
            + "  }\n"
            + "})();\n"
            + "</script>";
    }
}
