package io.jettra.flux.theme;

/**
 * PoliceTheme provides an authentic tactical cyber-surveillance visual theme for JettraFlux,
 * modeled directly after the interface and components of JettraStorePolice3D:
 * - Tactical midnight command navy canvas (#090d16) with subtle cyber grid
 * - Police Gold (#ffd700) primary actions, HUD headers and cluster badges
 * - Cyber Sky Blue (#00d4ff) telemetry streams, labels and node connections
 * - Neon Tactical Lime (#22c55e) online status and Alert Red (#ef4444) offline indicators
 * - High-legibility monospace metrics and typography ('JetBrains Mono', 'Segoe UI')
 * - Real-time surveillance radar sweep canvas in pure vanilla JavaScript
 * - Pure HTML, CSS, JavaScript (zero JavaFX or external UI libraries)
 */
public class PoliceTheme {

    public static ThemeData create() {
        return Police.create();
    }

    public static ThemeData create(ColorMode mode) {
        return Police.create(mode);
    }

    public static ThemeTokens getTokens(ColorMode mode) {
        return Police.getTokens(mode);
    }

    public static class Template {
        public static final String CustomCSS = "<style>\n"
            + "/* JettraStorePolice3D Tactical Cyber-Surveillance Design System */\n"
            + "@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&display=swap');\n"
            + "\n"
            + ":root {\n"
            + "  --police-gold: #ffd700;\n"
            + "  --police-gold-hover: #ffea00;\n"
            + "  --police-blue: #00d4ff;\n"
            + "  --police-blue-hover: #38bdf8;\n"
            + "  --police-lime: #22c55e;\n"
            + "  --police-red: #ef4444;\n"
            + "  --police-orange: #f59e0b;\n"
            + "  --police-bg: #090d16;\n"
            + "  --police-surface: #0f1526;\n"
            + "  --police-surface-alt: #141c30;\n"
            + "  --police-border: rgba(0, 212, 255, 0.35);\n"
            + "  --police-border-gold: rgba(255, 215, 0, 0.5);\n"
            + "  --police-text: #f8fafc;\n"
            + "  --police-text-muted: #94a3b8;\n"
            + "  --police-font: 'JetBrains Mono', 'Segoe UI', -apple-system, BlinkMacSystemFont, monospace, sans-serif;\n"
            + "  --background-color: #090d16 !important;\n"
            + "  --surface-color: #0f1526 !important;\n"
            + "  --on-surface-color: #f8fafc !important;\n"
            + "  --on-primary-color: #090d16 !important;\n"
            + "  --primary-color: #ffd700 !important;\n"
            + "}\n"
            + "\n"
            + "* {\n"
            + "  box-sizing: border-box;\n"
            + "}\n"
            + "\n"
            + "body, p, h1, h2, h3, h4, h5, h6, input, textarea, select, button, table, a, div {\n"
            + "  font-family: var(--police-font);\n"
            + "  -webkit-font-smoothing: antialiased;\n"
            + "  -moz-osx-font-smoothing: grayscale;\n"
            + "}\n"
            + "\n"
            + "/* Preserve icon font families */\n"
            + "i, .fa, .fas, .far, .fab, .bi, .material-icons, .material-symbols, [class*=\"fa-\"], [class*=\"bi-\"] {\n"
            + "  font-family: \"Font Awesome 5 Free\", \"FontAwesome\", \"bootstrap-icons\", \"Material Symbols Outlined\" !important;\n"
            + "  font-style: normal !important;\n"
            + "  display: inline-block !important;\n"
            + "}\n"
            + "\n"
            + "/* Body Canvas with Tactical Dark Navy & Cyber Grid */\n"
            + "body {\n"
            + "  background-color: #090d16 !important;\n"
            + "  background-image: \n"
            + "    linear-gradient(rgba(0, 212, 255, 0.04) 1px, transparent 1px),\n"
            + "    linear-gradient(90deg, rgba(0, 212, 255, 0.04) 1px, transparent 1px) !important;\n"
            + "  background-size: 32px 32px !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  margin: 0;\n"
            + "  padding: 0;\n"
            + "  overflow-x: hidden;\n"
            + "  position: relative;\n"
            + "}\n"
            + "\n"
            + "/* Custom Tactical Scrollbar */\n"
            + "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
            + "::-webkit-scrollbar-track { background: #090d16; }\n"
            + "::-webkit-scrollbar-thumb { background: #1e293b; border-radius: 4px; border: 1px solid rgba(0, 212, 255, 0.2); }\n"
            + "::-webkit-scrollbar-thumb:hover { background: #00d4ff; }\n"
            + "\n"
            + "/* Layout & Viewports */\n"
            + ".espresso-dashboard, .espresso-center, .espresso-main, .jettra-main-viewport, .professional-center {\n"
            + "  background-color: transparent !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Top Header Bar */\n"
            + ".espresso-top, .professional-top, .jettra-header, .police-header {\n"
            + "  background-color: #090d16 !important;\n"
            + "  border-bottom: 2px solid #ffd700 !important;\n"
            + "  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.8) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "}\n"
            + "\n"
            + "/* Sidebar Navigation */\n"
            + ".professional-left, .espresso-left, .jettra-sidebar, .police-sidebar {\n"
            + "  background-color: #0c111e !important;\n"
            + "  border-right: 1px solid rgba(0, 212, 255, 0.25) !important;\n"
            + "  box-shadow: 4px 0 20px rgba(0, 0, 0, 0.6) !important;\n"
            + "}\n"
            + "\n"
            + ".professional-left a, .professional-left p, .espresso-left a, .espresso-left p, .widgetlet-item {\n"
            + "  color: #94a3b8 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 10px 14px !important;\n"
            + "  margin-bottom: 4px;\n"
            + "  transition: all 0.2s ease;\n"
            + "  font-weight: 500;\n"
            + "  border: 1px solid transparent;\n"
            + "}\n"
            + "\n"
            + ".professional-left a:hover, .professional-left p:hover, .espresso-left a:hover, .espresso-left p:hover, .widgetlet-item:hover {\n"
            + "  background-color: rgba(0, 212, 255, 0.1) !important;\n"
            + "  color: #00d4ff !important;\n"
            + "  border-color: rgba(0, 212, 255, 0.35) !important;\n"
            + "  text-shadow: 0 0 8px rgba(0, 212, 255, 0.5);\n"
            + "  transform: translateX(3px);\n"
            + "}\n"
            + "\n"
            + ".professional-left a.active, .espresso-left a.active {\n"
            + "  background-color: rgba(255, 215, 0, 0.12) !important;\n"
            + "  color: #ffd700 !important;\n"
            + "  border-left: 3px solid #ffd700 !important;\n"
            + "  border-color: rgba(255, 215, 0, 0.4) !important;\n"
            + "  box-shadow: 0 0 12px rgba(255, 215, 0, 0.25);\n"
            + "  font-weight: 700;\n"
            + "}\n"
            + "\n"
            + "/* Tactical Police Cards & HUD Panels */\n"
            + ".espresso-card, .police-card, .police-hud-panel, .card {\n"
            + "  background: linear-gradient(180deg, #0f1526 0%, #090d16 100%) !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.35) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  padding: 20px !important;\n"
            + "  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.7), inset 0 1px 0 rgba(0, 212, 255, 0.2) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  position: relative;\n"
            + "  transition: border-color 0.25s, box-shadow 0.25s;\n"
            + "}\n"
            + "\n"
            + ".espresso-card:hover, .police-card:hover {\n"
            + "  border-color: rgba(0, 212, 255, 0.6) !important;\n"
            + "  box-shadow: 0 6px 24px rgba(0, 212, 255, 0.15), inset 0 1px 0 rgba(0, 212, 255, 0.3) !important;\n"
            + "}\n"
            + "\n"
            + "/* Police Action Buttons */\n"
            + ".espresso-button, .espresso-btn, .btn, .btn-primary, .police-btn-gold {\n"
            + "  background-color: #ffd700 !important;\n"
            + "  color: #090d16 !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 12px rgba(255, 215, 0, 0.4) !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  letter-spacing: 0.08em;\n"
            + "  padding: 10px 22px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".espresso-button:hover, .espresso-btn:hover, .btn:hover, .btn-primary:hover, .police-btn-gold:hover {\n"
            + "  background-color: #ffea00 !important;\n"
            + "  border-color: #ffea00 !important;\n"
            + "  box-shadow: 0 0 18px rgba(255, 215, 0, 0.65) !important;\n"
            + "  transform: translateY(-1px);\n"
            + "}\n"
            + "\n"
            + ".police-btn-blue, .espresso-btn-info, .btn-info {\n"
            + "  background-color: rgba(0, 212, 255, 0.12) !important;\n"
            + "  color: #00d4ff !important;\n"
            + "  border: 1px solid #00d4ff !important;\n"
            + "  box-shadow: 0 0 10px rgba(0, 212, 255, 0.3) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase;\n"
            + "  padding: 8px 18px !important;\n"
            + "  cursor: pointer;\n"
            + "  transition: all 0.2s ease;\n"
            + "}\n"
            + "\n"
            + ".police-btn-blue:hover, .espresso-btn-info:hover, .btn-info:hover {\n"
            + "  background-color: #00d4ff !important;\n"
            + "  color: #090d16 !important;\n"
            + "  box-shadow: 0 0 16px rgba(0, 212, 255, 0.6) !important;\n"
            + "}\n"
            + "\n"
            + ".police-btn-lime, .espresso-btn-success, .btn-success {\n"
            + "  background-color: #22c55e !important;\n"
            + "  color: #090d16 !important;\n"
            + "  border: 1px solid #22c55e !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 10px rgba(34, 197, 94, 0.4) !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  cursor: pointer;\n"
            + "}\n"
            + "\n"
            + ".police-btn-red, .espresso-btn-danger, .btn-danger {\n"
            + "  background-color: #ef4444 !important;\n"
            + "  color: #ffffff !important;\n"
            + "  border: 1px solid #ef4444 !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  box-shadow: 0 0 10px rgba(239, 68, 68, 0.4) !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  cursor: pointer;\n"
            + "}\n"
            + "\n"
            + "/* Form Inputs and Selects */\n"
            + ".espresso-textfield, input[type=\"text\"], input[type=\"password\"], input[type=\"search\"], select, textarea {\n"
            + "  background-color: #080c14 !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.35) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  font-family: var(--police-font) !important;\n"
            + "  border-radius: 6px !important;\n"
            + "  padding: 8px 12px !important;\n"
            + "  transition: border-color 0.2s, box-shadow 0.2s;\n"
            + "}\n"
            + "\n"
            + ".espresso-textfield:focus, input:focus, select:focus, textarea:focus {\n"
            + "  border-color: #ffd700 !important;\n"
            + "  box-shadow: 0 0 10px rgba(255, 215, 0, 0.45) !important;\n"
            + "  outline: none !important;\n"
            + "}\n"
            + "\n"
            + "/* DataTables & Data Grids */\n"
            + ".espresso-datatable, table {\n"
            + "  border-collapse: separate !important;\n"
            + "  border-spacing: 0 !important;\n"
            + "  width: 100% !important;\n"
            + "  background-color: #0f1526 !important;\n"
            + "  border: 1px solid rgba(0, 212, 255, 0.3) !important;\n"
            + "  border-radius: 8px !important;\n"
            + "  overflow: hidden !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable th, table th {\n"
            + "  background-color: #0a0f1d !important;\n"
            + "  color: #ffd700 !important;\n"
            + "  border-bottom: 2px solid #ffd700 !important;\n"
            + "  padding: 12px 16px !important;\n"
            + "  text-align: left !important;\n"
            + "  font-weight: 700 !important;\n"
            + "  text-transform: uppercase !important;\n"
            + "  font-size: 0.8rem !important;\n"
            + "  letter-spacing: 0.06em !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable td, table td {\n"
            + "  padding: 10px 16px !important;\n"
            + "  border-bottom: 1px solid rgba(0, 212, 255, 0.15) !important;\n"
            + "  color: #f8fafc !important;\n"
            + "  font-size: 0.9rem !important;\n"
            + "}\n"
            + "\n"
            + ".espresso-datatable tr:hover td, table tr:hover td {\n"
            + "  background-color: rgba(0, 212, 255, 0.08) !important;\n"
            + "}\n"
            + "\n"
            + "/* Tactical Badges & Pills */\n"
            + ".police-badge {\n"
            + "  display: inline-flex;\n"
            + "  align-items: center;\n"
            + "  gap: 6px;\n"
            + "  padding: 3px 10px;\n"
            + "  border-radius: 9999px;\n"
            + "  font-size: 0.75rem;\n"
            + "  font-weight: 700;\n"
            + "  letter-spacing: 0.05em;\n"
            + "  text-transform: uppercase;\n"
            + "}\n"
            + "\n"
            + ".police-badge-gold {\n"
            + "  color: #ffd700;\n"
            + "  border: 1px solid #ffd700;\n"
            + "  background-color: rgba(255, 215, 0, 0.12);\n"
            + "  box-shadow: 0 0 8px rgba(255, 215, 0, 0.25);\n"
            + "}\n"
            + "\n"
            + ".police-badge-blue {\n"
            + "  color: #00d4ff;\n"
            + "  border: 1px solid #00d4ff;\n"
            + "  background-color: rgba(0, 212, 255, 0.12);\n"
            + "  box-shadow: 0 0 8px rgba(0, 212, 255, 0.25);\n"
            + "}\n"
            + "\n"
            + ".police-badge-lime {\n"
            + "  color: #22c55e;\n"
            + "  border: 1px solid #22c55e;\n"
            + "  background-color: rgba(34, 197, 94, 0.12);\n"
            + "  box-shadow: 0 0 8px rgba(34, 197, 94, 0.25);\n"
            + "}\n"
            + "\n"
            + ".police-badge-red {\n"
            + "  color: #ef4444;\n"
            + "  border: 1px solid #ef4444;\n"
            + "  background-color: rgba(239, 68, 68, 0.12);\n"
            + "  box-shadow: 0 0 8px rgba(239, 68, 68, 0.25);\n"
            + "}\n"
            + "\n"
            + "/* Real-Time Pulse Animation for Node Status */\n"
            + "@keyframes police-pulse {\n"
            + "  0% { transform: scale(0.95); opacity: 0.7; }\n"
            + "  50% { transform: scale(1.2); opacity: 1; }\n"
            + "  100% { transform: scale(0.95); opacity: 0.7; }\n"
            + "}\n"
            + "\n"
            + ".police-dot-active {\n"
            + "  display: inline-block;\n"
            + "  width: 8px;\n"
            + "  height: 8px;\n"
            + "  border-radius: 50%;\n"
            + "  background-color: #22c55e;\n"
            + "  box-shadow: 0 0 8px #22c55e;\n"
            + "  animation: police-pulse 1.8s infinite;\n"
            + "  margin-right: 6px;\n"
            + "}\n"
            + "\n"
            + ".police-dot-alert {\n"
            + "  display: inline-block;\n"
            + "  width: 8px;\n"
            + "  height: 8px;\n"
            + "  border-radius: 50%;\n"
            + "  background-color: #ef4444;\n"
            + "  box-shadow: 0 0 8px #ef4444;\n"
            + "  margin-right: 6px;\n"
            + "}\n"
            + "\n"
            + "/* Multinode Active Indicators */\n"
            + ".police-multinode-on {\n"
            + "  color: #ffd700 !important;\n"
            + "  border: 1px solid #ffd700 !important;\n"
            + "  background: rgba(255, 215, 0, 0.15) !important;\n"
            + "  padding: 3px 8px;\n"
            + "  border-radius: 4px;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.8rem;\n"
            + "}\n"
            + "\n"
            + ".police-multinode-off {\n"
            + "  color: #f59e0b !important;\n"
            + "  border: 1px solid #f59e0b !important;\n"
            + "  background: rgba(245, 158, 11, 0.15) !important;\n"
            + "  padding: 3px 8px;\n"
            + "  border-radius: 4px;\n"
            + "  font-weight: 700;\n"
            + "  font-size: 0.8rem;\n"
            + "}\n"
            + "\n"
            + "/* Police Surveillance Radar Canvas */\n"
            + "#police-radar-canvas {\n"
            + "  position: fixed;\n"
            + "  top: 0;\n"
            + "  left: 0;\n"
            + "  width: 100vw;\n"
            + "  height: 100vh;\n"
            + "  z-index: 0;\n"
            + "  pointer-events: none;\n"
            + "  opacity: 0.45;\n"
            + "}\n"
            + "</style>";

        public static final String CustomJS = "<script>\n"
            + "(function() {\n"
            + "  function initPoliceRadar() {\n"
            + "    if (document.getElementById('police-radar-canvas')) return;\n"
            + "    var canvas = document.createElement('canvas');\n"
            + "    canvas.id = 'police-radar-canvas';\n"
            + "    document.body.prepend(canvas);\n"
            + "\n"
            + "    var ctx = canvas.getContext('2d');\n"
            + "    var w, h, cx, cy, radius;\n"
            + "    var angle = 0;\n"
            + "\n"
            + "    function resize() {\n"
            + "      w = canvas.width = window.innerWidth;\n"
            + "      h = canvas.height = window.innerHeight;\n"
            + "      cx = w - 160;\n"
            + "      cy = 160;\n"
            + "      radius = 120;\n"
            + "    }\n"
            + "    resize();\n"
            + "    window.addEventListener('resize', resize);\n"
            + "\n"
            + "    var blips = [\n"
            + "      { r: 40, theta: 0.8, color: '#22c55e', label: 'NODE-1' },\n"
            + "      { r: 75, theta: 2.2, color: '#22c55e', label: 'NODE-2' },\n"
            + "      { r: 95, theta: 4.1, color: '#ef4444', label: 'NODE-3' }\n"
            + "    ];\n"
            + "\n"
            + "    var lastTime = 0;\n"
            + "    function render(time) {\n"
            + "      requestAnimationFrame(render);\n"
            + "      if (time - lastTime < 33) return; // ~30 fps cap\n"
            + "      lastTime = time;\n"
            + "\n"
            + "      ctx.clearRect(0, 0, w, h);\n"
            + "\n"
            + "      // Radar Background & Concentric Rings\n"
            + "      ctx.save();\n"
            + "      ctx.strokeStyle = 'rgba(0, 212, 255, 0.18)';\n"
            + "      ctx.lineWidth = 1;\n"
            + "\n"
            + "      for (var r = 30; r <= radius; r += 30) {\n"
            + "        ctx.beginPath();\n"
            + "        ctx.arc(cx, cy, r, 0, Math.PI * 2);\n"
            + "        ctx.stroke();\n"
            + "      }\n"
            + "\n"
            + "      // Crosshairs\n"
            + "      ctx.beginPath();\n"
            + "      ctx.moveTo(cx - radius - 10, cy);\n"
            + "      ctx.lineTo(cx + radius + 10, cy);\n"
            + "      ctx.moveTo(cx, cy - radius - 10);\n"
            + "      ctx.lineTo(cx, cy + radius + 10);\n"
            + "      ctx.stroke();\n"
            + "\n"
            + "      // Sweep Beam\n"
            + "      ctx.beginPath();\n"
            + "      ctx.moveTo(cx, cy);\n"
            + "      ctx.arc(cx, cy, radius, angle - 0.25, angle);\n"
            + "      ctx.closePath();\n"
            + "      var grad = ctx.createRadialGradient(cx, cy, 0, cx, cy, radius);\n"
            + "      grad.addColorStop(0, 'rgba(0, 212, 255, 0.25)');\n"
            + "      grad.addColorStop(1, 'rgba(0, 212, 255, 0.0)');\n"
            + "      ctx.fillStyle = grad;\n"
            + "      ctx.fill();\n"
            + "\n"
            + "      // Leading sweep line\n"
            + "      ctx.beginPath();\n"
            + "      ctx.moveTo(cx, cy);\n"
            + "      ctx.lineTo(cx + Math.cos(angle) * radius, cy + Math.sin(angle) * radius);\n"
            + "      ctx.strokeStyle = 'rgba(0, 212, 255, 0.5)';\n"
            + "      ctx.stroke();\n"
            + "\n"
            + "      // Blips\n"
            + "      for (var i = 0; i < blips.length; i++) {\n"
            + "        var b = blips[i];\n"
            + "        var bx = cx + Math.cos(b.theta) * b.r;\n"
            + "        var by = cy + Math.sin(b.theta) * b.r;\n"
            + "        ctx.beginPath();\n"
            + "        ctx.arc(bx, by, 3.5, 0, Math.PI * 2);\n"
            + "        ctx.fillStyle = b.color;\n"
            + "        ctx.shadowColor = b.color;\n"
            + "        ctx.shadowBlur = 6;\n"
            + "        ctx.fill();\n"
            + "        ctx.shadowBlur = 0;\n"
            + "      }\n"
            + "\n"
            + "      ctx.restore();\n"
            + "      angle = (angle + 0.025) % (Math.PI * 2);\n"
            + "    }\n"
            + "    requestAnimationFrame(render);\n"
            + "  }\n"
            + "  if (document.readyState === 'loading') {\n"
            + "    document.addEventListener('DOMContentLoaded', initPoliceRadar);\n"
            + "  } else {\n"
            + "    initPoliceRadar();\n"
            + "  }\n"
            + "})();\n"
            + "</script>";
    }
}
